# -*- coding: utf-8 -*-
# Deployment settings for Blaster.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.5/s3e/makefile_builder/mkb.py', 'c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/Blaster.mkb', '--deploy-only', '--hub-data', 'C:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/project_Blaster/mkb-wp8.txt', '--buildenv=VC11', '--buildenv-toolset=WP8']
mkb = 'c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/Blaster.mkb'
mkf = ['c:\\marmalade\\7.5\\s3e\\s3e-default.mkf', 'c:\\marmalade\\7.5\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.5\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.5\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.5\\modules\\third_party\\zlib\\zlib.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Blaster'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Blaster'
    long_caption = 'Blaster'
    version = [0, 0, 1]
    config = ['c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/data/app.icf']
    data_dir = 'c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/data'
    mkb_dir = 'c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster'
    iphone_link_lib = []
    osx_ext_dll = []
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws8_extra_res = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    iphone_extra_plist = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_extra_packages = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'wp8-x86' : {
                   'debug'   : r'c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/build_blaster_vc11_wp8toolset/Debug_Blaster_VC11_WP8TOOLSET_x86/Blaster.s86',
                   'release' : r'c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/build_blaster_vc11_wp8toolset/Release_Blaster_VC11_WP8TOOLSET_x86/Blaster.s86',
                 },
         'wp8-arm' : {
                   'debug'   : r'c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/build_blaster_vc11_wp8toolset/Debug_Blaster_VC11_WP8TOOLSET_arm/Blaster.s86',
                   'release' : r'c:/Users/blogs_000/Documents/Visual Studio 2012/Projects/SDL/SDL/Blaster/build_blaster_vc11_wp8toolset/Release_Blaster_VC11_WP8TOOLSET_arm/Blaster.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
